default: &DEFAULT
  :db: <%= ENV.fetch('SESSION_REDIS_DB_INDEX') %>

session: &SESSION
  <<: *DEFAULT
  :host: <%= ENV.fetch('SESSION_REDIS_HOST') %>
  :port: <%= ENV.fetch('SESSION_REDIS_PORT', 6379) %>
  :expires_in: <%= 2.hours %>

cache:
  <<: *SESSION
